<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ArrayCollection $categories
     * @return mixed
     */
    public function findAllDocumentsByCategories(ArrayCollection $categories)
    {
        $ids = $categories->map(function($cat){ return $cat->getId();})->toArray();

        if (count($ids) == 0){
            return new ArrayCollection();
        }

        $qb =  $this->createQueryBuilder("dc");
        return $qb->where($qb->expr()->in("dc.category", $ids))
            ->getQuery()->getResult()
        ;
    }
}
